export const PATHS = {
  HOME: "/",
  PAGE404: "*",
  PRODUCTS: "/products",
  PRODUCTS_CAT: "/products/:categoryName",
  PRODUCT: "/product/:productId",
  BASKET: "/basket",
  CHECKOUT: "/checkout",
  PAYMENT: "/payment",
  LOGIN: "/login",
  REGISTER: "/resgister",
  CONTACTUS: "/contact-us",
  DASHBOARD: "/dashboard",
  DASHBOARD_ORDERS: "/dashboard/orders",
  DASHBOARD_PRODUCTS: "/dashboard/products",
  DASHBOARD_CATEGORIES: "/dashboard/categories",
  DASHBOARD_USERS: "/dashboard/users",
  DASHBOARD_SETTINGS: "/dashboard/settings",
  DASHBOARD_EXIT: "/dashboard/logout",
};
