const faTexts = {
  home: "صفحه نخست",
  products: "محصولات",
  blog: "بلاگ",
  login: "ورود",
  contactus: "ارتباط با ما",
  search: "جستجو",
  404: "متاسفانه صفحه مورد نظر یافت نشد",
  backToHome: "برای رفتن به صفحه نخست روی دکمه زیر کلیک کنید",
  emailInput: "ایمیل",
  username: "نام کاربری",
  minUserName: "نام کاربری میبایست بیشتر از 3 حرف باشد",
  usernameRequired: "وارد کردن نام کاربری الزامی هست",
  wrongUserName: "نام کاربری وارد شده نامعتبر هست",
  passInput: "رمز عبور",
  minPassword: "رمز عبور میبایست بیشتر از 3 حرف باشد",
  wrongEmail: "ایمیل وارد شده نامعتبر هست",
  emailRequired: "وارد کردن ایمیل الزامی هست",
  passRequired: "وارد کردن رمزعبور الزامی هست",
  footerText:
    " در ورتو ‌استایل می‌توانید همه آنچه مرتبط با مد و پوشاک از انواع لباس زنانه، لباس مردانه و لباس بچگانه گرفته تا کیف و کفش و اکسسوری را با تخفیف ویژه در حراج ها، پیدا کنید و به سادگی یک ست کامل از جدیدترین‌ برندهای معتبر را بخرید.",
  storeName: "فروشگاه اینترنتی مد و لباس ورتواستایل",
  copyRight: "تمامی حقوق متعلق به ورتو استایل هست  ",
  offer: "پیشنهاد شگفت انگیز",
  connectionLost:
    "متاسفانه اتصال شما به وب سایت قطع شده است. لطفاً دوباره سعی کنید.",
  refresh: "بارگذاری مجدد",
  menClothe: " پیراهن مردانه",
  menShoes: "کفش مردانه",
  menSport: "ورزشی مردانه",
  womenClothe: "مانتو زنانه",
  womenShoes: "کفش زنانه",
  womenSport: "ورزشی زنانه",
  orders: "سفارشات",

  entityAndPrice: "موجودی و قیمت ها",
  productImage: "عکس محصول",
  producName: "نام محصول",
  productPrice: "قیمت",
  productCategory: "دسته بندی",
  productSubCateory: "زیر دسته بندی",
  productBrand: "برند",
  productQuantity: "تعداد محصول",
  productDescription: "توضیحات محصول",
  dashborad: "داشبورد",
};

export default faTexts;
